refactor: main
hackclub/counterspell pull request #1
Opened 2024-09-29 00:23 UTC by NeonGamerBot-QK

- removed unused tests, and webvitals since https://github.com/hackclub/counterspell/commit/dbfd6c08ecd23d5ca78751c1e64f2e070c3ed35b exists.
- fix manifest.json to use correct name & desc

*note: zeon is my bot and only linted the files with prettier*

2024-09-29 05:29 UTC, samdev-7 requested changes

2024-09-29 05:29 UTC, samdev-7 commented on src/reportWebVitals.js
deployment is failing due to this file missing, it seems

2024-09-29 05:36 UTC, NeonGamerBot-QK commented
Fixed @samdev-7

2024-10-03 01:23 UTC, NeonGamerBot-QK commented
@samdev-7 could u find the err? (i cant see vercels thing)

2024-10-03 04:15 UTC, samdev-7 commented
Hopefully this helps! 
![Uploading image.png…]()

2024-10-03 04:55 UTC, NeonGamerBot-QK commented
@samdev-7 fixed.

2024-10-05 03:24 UTC, samdev-7 commented
Thanks for the PR but I won't be merging this. I'll be formatting these files as I go, and the format seems to conflict with what I have set up (prettier default).

2024-10-05 03:24 UTC, closed without merging