Adding Counterspell Valenzuela City
hackclub/counterspell pull request #113
Opened 2024-11-04 10:37 UTC by Cai0n29

Adding pages and components of Counterspell Valenzuela

2024-11-05 04:07 UTC, samdev-7 requested changes
Almost there!

2024-11-05 04:07 UTC, samdev-7 commented on components/ValenzuelaCity/About.js
> +              schoolers happening in Example City where{" "}
You forgot to change out the Example City here!

2024-11-06 01:59 UTC, Cai0n29 commented
Done! I also added the fill out forms

2024-11-06 03:55 UTC, samdev-7 approved these changes

2024-11-06 04:00 UTC, merged