Added CounterSpell Wolverhampton
hackclub/counterspell pull request #114
Opened 2024-11-04 22:03 UTC by tobilobasalawu

Added  CounterSpell Wolverhampton Website 🎉.

**Changes**
- I made a copy of the example components, made the required changes, and renamed it Wolverhampton.
- I made a copy of the example-city.js file, made required changes, and renamed it to Wolverhampton

2024-11-05 04:06 UTC, samdev-7 requested changes

2024-11-05 04:06 UTC, samdev-7 commented on components/Schedule.js
Seems like you edited the wrong file. Please revert these changes.

2024-11-05 04:06 UTC, samdev-7 commented on package-lock.json
Please don't edit this file. Thanks!

2024-11-05 04:06 UTC, samdev-7 commented on package.json
Please don't edit this file. Thanks!

2024-11-05 04:06 UTC, samdev-7 commented on yarn.lock
Please don't edit this file. Thanks!

2024-11-05 04:07 UTC, lachlanjc commented
#### 📝 Changed routes:


| [**/wolverhampton**](https://counterspell-jpppm7bll.hackclub.dev/wolverhampton) |
|:-:|
|<a href="https://counterspell-jpppm7bll.hackclub.dev/wolverhampton"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/S6keDzMtYowlWJzxKA1CstmU4aJ3bDuG4u4aqrCz2Vr7HHHN1Ygi-LsuYiSD-UWK5lp1A8S9WVfpBi2ugJFbMQ.png&w=600" alt="Screenshot of /wolverhampton" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/27CFpCSL84Ylszp2A-MRfIDytEah0lLpqq6cGkPYGquPk4MgctAV3B1mUahlQj63ILO8NvpovDKtBzoqPxtjsQ.png">(view full size)</a> |







Commit aac52964767cc7030aeddca5286d9806daa7a26b (https://counterspell-jpppm7bll.hackclub.dev).

2024-11-05 04:07 UTC, samdev-7 commented
A few more changes and it'll be good to go!

2024-11-06 04:01 UTC, samdev-7 requested changes

2024-11-06 04:01 UTC, samdev-7 commented on components/Schedule.js
Please revert the changes on this file, thanks!

2024-11-06 04:01 UTC, samdev-7 commented on package-lock.json
Still the same issue, please don't create unneeded file. Thanks!

2024-11-06 17:39 UTC, merged