Added logo, sponsors, forms
hackclub/counterspell pull request #119
Opened 2024-11-06 01:04 UTC by GaoYeGithub

2024-11-06 04:00 UTC, samdev-7 requested changes
Note: When committing, you can choose to exclude certain files!

2024-11-06 04:00 UTC, samdev-7 commented on Counterspell Toronto package.json
Please don't edit this file and revert your change.

2024-11-06 04:00 UTC, samdev-7 commented on Counterspell Toronto yarn.lock
Please don't edit this file and revert your change.

2024-11-06 04:00 UTC, samdev-7 commented on package-lock.json
Please don't edit this file and revert your change.

2024-11-09 05:36 UTC, samdev-7 approved these changes

2024-11-09 05:37 UTC, samdev-7 commented on components/Toronto/Locations.js
> +import Subscribe from "./Subscribe";
Seems like this change is making the code error. Once this is fixed it's good to be merged!

2024-11-09 05:38 UTC, samdev-7 requested changes

2024-11-09 05:38 UTC, samdev-7 commented on components/Toronto/Locations.js
> +import Subscribe from "./Subscribe";
Seems like this change is making the code error. Once this is fixed it's good to be merged!

2024-11-09 18:46 UTC, regular030 commented
@samdev-7 It should be fixed now

2024-11-10 02:14 UTC, samdev-7 approved these changes

2024-11-10 02:15 UTC, lachlanjc commented
#### 📝 Changed routes:


| [**/toronto**](https://counterspell-q8dbp14i5.hackclub.dev/toronto) |
|:-:|
|<a href="https://counterspell-q8dbp14i5.hackclub.dev/toronto"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/1IkoDPuFI3zzjYZ60o1Rxs-7U4BZpAB0exMkSoFw34HR1jCYnE70EW_VEfeHsYGxA5DL5j_cSFbz-el2QVVnuQ.png&w=600" alt="Screenshot of /toronto" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/MJOvsB-MkI7uWFfzrr0U-59OOcgRBULEHGCn4FRCPeAPVb_HYAvj7IXgQky44YFUYaDmFwtFRaRrws3zOEFhwQ.png">(view full size)</a> |







Commit 9d7d490daf092812c4b8bff35d41e21d9ebeb7e2 (https://counterspell-q8dbp14i5.hackclub.dev).

2024-11-10 02:15 UTC, merged