Counterspell chennai
hackclub/counterspell pull request #137
Opened 2024-11-10 15:40 UTC by Vipremigini

Ignore the first 3 commits

2024-11-11 05:15 UTC, samdev-7 requested changes
Almost there! A few more changes.

2024-11-11 05:15 UTC, samdev-7 commented on components/Chennai/Guilds.js
> +            activities/challenges throughout Counterspell Example City!
```suggestion
            activities/challenges throughout Counterspell Chennai!
```

2024-11-11 05:15 UTC, samdev-7 commented on components/Chennai/Hero.js
> +                NOVEMBER 23-24, 2024 • EXAMPLE CITY
```suggestion
                NOVEMBER 23-24, 2024 • CHENNAI
```

2024-11-11 05:15 UTC, samdev-7 commented on pages/Chennai.js
You'll need to change the filename of this to be lowercase, so chennai.js.

2024-11-11 05:18 UTC, lachlanjc commented
#### 📝 Changed routes:


| [**/Chennai**](https://counterspell-h7314rzfr.hackclub.dev/Chennai) |
|:-:|
|<a href="https://counterspell-h7314rzfr.hackclub.dev/Chennai"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/zIx29LqPMQyP35a27A2K5-ALZo1wIV1DZux8c32vaR_q8f4u5_uxt-VgDXEmAZSzirrc3345wheqCXlaEAYj4w.png&w=600" alt="Screenshot of /Chennai" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/oXPzqi4mlOwGOmX4aI4shySRLNJUCTCYAOzkXi4PM83AVCHQTlEtx4uF8vBwJTbBcG1jEwIfD61EKd8UjwhweA.png">(view full size)</a> |







Commit d526a8055f84bc76ee0e6c94429421ccf55c31b2 (https://counterspell-h7314rzfr.hackclub.dev).

2024-11-11 05:43 UTC, Vipremigini commented
Made the requested changes

2024-11-12 08:33 UTC, merged

2024-11-12 08:45 UTC, Vipremigini commented
thank you