add Vancouver
hackclub/counterspell pull request #170
Opened 2024-11-15 19:57 UTC by CoderLogy

2024-11-16 02:54 UTC, samdev-7 requested changes

2024-11-16 02:54 UTC, samdev-7 commented on .replit
Please don't commit this file! Could you revert this change?

2024-11-16 02:54 UTC, samdev-7 commented on README.md
Please do not modify files that are not your city!

2024-11-16 04:37 UTC, CoderLogy commented
done @samdev-7 fixed the problems

2024-11-16 22:47 UTC, CoderLogy commented
Please let me know

2024-11-17 23:01 UTC, samdev-7 approved these changes

2024-11-17 23:09 UTC, CoderLogy commented
Why it got canceled @samdev-7

2024-11-17 23:11 UTC, CoderLogy commented
Please approve it

2024-11-18 01:05 UTC, lachlanjc commented
#### 📝 Changed routes:


| [**/vancouver**](https://counterspell-ja08s9y70.hackclub.dev/vancouver) |
|:-:|
|<a href="https://counterspell-ja08s9y70.hackclub.dev/vancouver"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/qCeZ0MAl1YnrANl_zVl0SdLlpTkvvkhHas_2FPj23c5NdWJTMkO9SrTpbI1_jY_m3BxQjXAYOKI3yhtdNQ5cUA.png&w=600" alt="Screenshot of /vancouver" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/hzY9oNb3RgSRQa5YFcmWxE5KloDBJPiezcQ9iUapqCyp0C7J0F5z_b3UsB0B2CQDZkQnsLl-vfiCLpPJLS2xfw.png">(view full size)</a> |







Commit 1a054a73d0da1d94d071d2f663d7771487916b49 (https://counterspell-ja08s9y70.hackclub.dev).

2024-11-18 02:35 UTC, CoderLogy commented
But it still shows this 
![image](https://github.com/user-attachments/assets/15c99277-fc39-4e8d-a188-04c1ef4e746f)

2024-11-18 18:12 UTC, CoderLogy commented
please merge the repo @samdev-7 @lachlanjc

2024-11-19 03:16 UTC, merged