Added all the basic stuff
hackclub/counterspell pull request #22
Opened 2024-10-10 20:53 UTC by GaoYeGithub

2024-10-10 20:54 UTC, lachlanjc commented
#### 📝 Changed routes:


| [**/toronto**](https://counterspell-6olfdup1s.hackclub.dev/toronto) |
|:-:|
|<a href="https://counterspell-6olfdup1s.hackclub.dev/toronto"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/RDL-8L7OqH_orWe0-bMt8NWW9GUcuzTmtaCVjirfYotri3JK0Ka3nrvQg1pHMF9wiFCBkNyfxW40D1CPK4tywg.png&w=600" alt="Screenshot of /toronto" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/wu-z6KhM5xhbUsdtpQ3ffSlqcaBWtgsWmpNroAnAKia878sHvbMWxl3dpOEyZoHsy3s5GqECjw7ihlrss3N1jg.png">(view full size)</a> |







Commit 0bccf7749fd20b531d8d9398d1aaa85b6b061b8f (https://counterspell-6olfdup1s.hackclub.dev).

2024-10-12 00:44 UTC, samdev-7 requested changes
Some more changes and it's good to go. Let me know if you need anything!

2024-10-12 00:44 UTC, samdev-7 commented on package.json
Please revert the change to this file.

2024-10-12 00:44 UTC, samdev-7 commented on package-lock.json
Please revert the change to this file.

2024-10-12 00:44 UTC, samdev-7 commented on yarn.lock
Sorry for being picky, please revert the change to this file.

2024-10-12 00:44 UTC, samdev-7 commented on .yarnrc.yml
Please revert the change to this file, only change what's needed.

2024-10-12 00:44 UTC, samdev-7 commented on .gitattributes
Please revert the change to this file.

2024-10-12 00:44 UTC, samdev-7 commented on components/Schedule.js
I don't think this was intentional, you should be editing components/Toronto/Schedule.js instead.

Please revert this change.

2024-10-12 00:44 UTC, samdev-7 commented on components/Toronto/Locations.js
> +        <Subscribe eventName="Example City" />
Please replace this with Toronto

2024-10-12 19:31 UTC, GaoYeGithub commented
I think I reverted all the things, please tell me if I missed any!

2024-10-12 21:59 UTC, samdev-7 requested changes
A few more changes need to be reverted, sorry!

2024-10-12 21:59 UTC, samdev-7 commented on components/Schedule.js
Seems like this file was still changed for some reason.

2024-10-12 21:59 UTC, samdev-7 commented on yarn.lock
This file still needs to be reverted.

2024-10-12 22:03 UTC, GaoYeGithub commented on yarn.lock
Hmm that weird it looks the same to me, lemme me redo the two files
![image](https://github.com/user-attachments/assets/3d9d6927-dc1c-4220-a2dd-8c1c034b8908)

2024-10-12 22:05 UTC, GaoYeGithub commented on yarn.lock
I downloaded and move it into my own file but nothing changed
![image](https://github.com/user-attachments/assets/69ef5550-bb4f-4203-bd91-fd552fab3f25)

2024-10-12 22:08 UTC, GaoYeGithub commented
Sorry it should be right now, can you double check?

2024-10-12 22:10 UTC, samdev-7 requested changes
Almost! Let me know if you need any help.

p.s. If you're using VS code, you can commit only the files you want by manually clicking the plus sign next to the name in the version control tab!

2024-10-12 22:10 UTC, samdev-7 commented on package.json
This has been changed now and needs reverting.

2024-10-12 22:10 UTC, samdev-7 commented on package.json
This has been changed now and needs reverting.

2024-10-12 22:10 UTC, samdev-7 commented on components/Schedule.js
> +}
The empty line at the end of the file was removed and needs to be added back.

2024-10-12 22:11 UTC, samdev-7 commented on yarn.lock
It just needs a blank line added to the end of the file.

2024-10-12 22:28 UTC, GaoYeGithub commented
Is it correct now?

2024-10-12 22:35 UTC, samdev-7 approved these changes

2024-10-12 22:36 UTC, samdev-7 commented
Yup, thanks!

2024-10-12 22:36 UTC, merged