Add Counterspell Santiago
hackclub/counterspell pull request #23
Opened 2024-10-10 21:23 UTC by Monoverde888

awesome event im really excited

2024-10-10 21:23 UTC, Monoverde888 commented
oops i should remove the package lock

2024-10-10 21:24 UTC, lachlanjc commented
#### 📝 Changed routes:


| [**/santiago**](https://counterspell-qzgxgf7ky.hackclub.dev/santiago) |
|:-:|
|<a href="https://counterspell-qzgxgf7ky.hackclub.dev/santiago"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/NfU5h04ysicSUfrakN4bqKhewggYzjJtrGWeIr_01KNqpR2F9-mRwJl-C9f7pE17zND0LlhwMm39hWMqKk6dNw.png&w=600" alt="Screenshot of /santiago" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/cX4jmJT2oo8CruIe0uOqEDNmXzSNGMEYBx7dHpCiVhSL8NwWdpGnNQ_ioMmpM5Be0lRuoFFJ8m1AE7Ic_hLuXQ.png">(view full size)</a> |







Commit 1a045a5eb661976d077a838ea009e89ddae1a82a (https://counterspell-qzgxgf7ky.hackclub.dev).

2024-10-12 00:41 UTC, samdev-7 requested changes
Almost there, some more changes and then it's good to go!

Also, are the flags supposed to be where they are? It looks a bit off when I scroll.

2024-10-12 00:41 UTC, samdev-7 commented on yarn.lock
Could you revert these changes?

2024-10-12 00:58 UTC, Monoverde888 commented on yarn.lock
done!

2024-10-12 00:58 UTC, Monoverde888 commented
and yeah the flags are kinda wonky but it doesnt really matter

2024-10-12 01:16 UTC, samdev-7 approved these changes

2024-10-12 01:18 UTC, merged