Added Counterspell Phoenix
hackclub/counterspell pull request #27
Opened 2024-10-11 14:24 UTC by pizzalover125

2024-10-11 14:25 UTC, lachlanjc commented
#### 📝 Changed routes:


| [**/phoenix**](https://counterspell-f3et1qwi1.hackclub.dev/phoenix) |
|:-:|
|<a href="https://counterspell-f3et1qwi1.hackclub.dev/phoenix"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/iD9inxXo_8pRk9rp0uKBXjwnI8aMgTOnKyi55DubZrkAsquz5TNtFhP7L23l9o9CLcsBUUUPOMO1xUQnVKsdlQ.png&w=600" alt="Screenshot of /phoenix" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/VDVui_sup0HXmEeac339ertn7qrwtXkIJICbtmtIQtE0CU5cX40oozHxsqHuaXz6z1pF_p1JrII920YSvjI2vA.png">(view full size)</a> |







Commit ac1690c09a22f613b20dca795761cf5ce15c6b17 (https://counterspell-f3et1qwi1.hackclub.dev).

2024-10-12 00:35 UTC, samdev-7 requested changes
Almost there! Some quick fixes.

2024-10-12 00:35 UTC, samdev-7 commented on components/Phoenix/Guilds.js
> +            activities/challenges throughout Counterspell Example City!
You might want to change this!

2024-10-12 00:35 UTC, samdev-7 commented on components/Phoenix/Steps.js
> +              Counterspell Example City will go on for{" "}
You might want to change this!

2024-10-12 14:53 UTC, pizzalover125 commented
Let me know what else I need to change :)

2024-10-12 22:00 UTC, samdev-7 approved these changes

2024-10-12 22:01 UTC, merged