Added Counterspell Manila
hackclub/counterspell pull request #41
Opened 2024-10-12 08:07 UTC by romalescarl17

2024-10-12 08:08 UTC, lachlanjc commented
#### 📝 Changed routes:


| [**/manila**](https://counterspell-m6g7f1d13.hackclub.dev/manila) |
|:-:|
|<a href="https://counterspell-m6g7f1d13.hackclub.dev/manila"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/zvvVYIvOWsYy9rJ030fIn7UDULujt3u8lTUCACUD5UsKdV0XhvPEkxlUlDsxT0WuNVi4Ztq29k5ZFrQxWCgYJA.png&w=600" alt="Screenshot of /manila" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/xoD4Bn6MvcjoqGPDkQuniLtbRd3xpupRvQSupayS1QP6SNF2l4vvDicMMnEvXkDYPw3sGQjlOAkkNIA32YxQMA.png">(view full size)</a> |







Commit 28c865ee6a8441b45ec2ef110abea4c3c0cd8a49 (https://counterspell-m6g7f1d13.hackclub.dev).

2024-10-12 22:02 UTC, samdev-7 requested changes
A few leftover "Example City"s need to be changed. I've left suggestions.

2024-10-12 22:02 UTC, samdev-7 commented on components/Manila/Steps.js
> +                text="Sign up for Counterspell Example city"
```suggestion
                text="Sign up for Counterspell Manila"
```

2024-10-12 22:02 UTC, samdev-7 commented on components/Manila/Steps.js
> +              Counterspell Example City will go on for{" "}
```suggestion
              Counterspell Manila will go on for{" "}
```

2024-10-13 03:08 UTC, samdev-7 requested changes

2024-10-13 03:08 UTC, samdev-7 commented on components/events.json
Hi! Can you move this into the Manila folder?

2024-10-13 03:17 UTC, romalescarl17 commented on components/events.json
Yeah, sure. Please wait :)

2024-10-13 03:23 UTC, romalescarl17 commented on components/events.json
Moved it :)

2024-10-13 03:29 UTC, samdev-7 approved these changes

2024-10-13 03:30 UTC, merged