Add Counterspell Dhaka
hackclub/counterspell pull request #44
Opened 2024-10-12 13:30 UTC by tamzid10001

2024-10-12 13:39 UTC, tamzid10001 commented
> **The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)
> 
> Name	Status	Preview	Comments	Updated (UTC)
> **counterspell**	❌ Failed ([Inspect](https://vercel.com/hackclub/counterspell/13ZCncwBYzw26HL1H9hCJUuCh9Wf))			Oct 12, 2024 1:35pm

2024-10-12 22:03 UTC, samdev-7 approved these changes

2024-10-12 22:07 UTC, lachlanjc commented
#### 📝 Changed routes:


| [**/dhaka**](https://counterspell-r2mullh2g.hackclub.dev/dhaka) |
|:-:|
|<a href="https://counterspell-r2mullh2g.hackclub.dev/dhaka"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/_WCKpqOzq7CcHUkiORYvstw0ZA_EiXA-pmuflJnadt0C54I_O954zsr1DDvHt2mZYCrQX2LVG2RJS7F9dlxfEw.png&w=600" alt="Screenshot of /dhaka" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/_ppfBfPHGBTIXQht8WJpUKdFWJBKubLSkvWpqPMC1EDhKXAfic4uucnGmYmWk4xVL3YVC5JWJzVJzyLhmu6uQQ.png">(view full size)</a> |







Commit 4513fa04dd56a3cdccf63ada7544d0d85e21ec70 (https://counterspell-r2mullh2g.hackclub.dev).

2024-10-12 22:08 UTC, samdev-7 requested changes
It seems like you copied the wrong folder, make sure you copy the ExampleCity folder and edit it from there.

2024-10-14 22:32 UTC, samdev-7 requested changes
Almost good to go. I've left some suggestions of edits you missed.

2024-10-14 22:32 UTC, samdev-7 commented on components/Dhaka/About.js
> +              schoolers happening in Example City where{" "}
```suggestion
              schoolers happening in Dhaka where{" "}
```

2024-10-14 22:32 UTC, samdev-7 commented on components/Dhaka/Hero.js
> +                NOVEMBER 23-24, 2024 • EXAMPLE CITY
```suggestion
                NOVEMBER 23-24, 2024 • DHAKA
```

2024-10-16 10:47 UTC, samdev-7 approved these changes

2024-10-16 10:48 UTC, merged