Added Counterspell Casablanca!
hackclub/counterspell pull request #49
Opened 2024-10-13 19:06 UTC by slippyishappy

The Counterspell Casablanca Hackathon Website.

2024-10-13 19:07 UTC, lachlanjc commented
#### 📝 Changed routes:


| [**/casablanca**](https://counterspell-em14esi6b.hackclub.dev/casablanca) |
|:-:|
|<a href="https://counterspell-em14esi6b.hackclub.dev/casablanca"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/oC0pUrbAYrAQD2DagZ5xk-d8kpdPi2LVnlfFPcX0eRtOVDJmcqu1izWFoqJR6THi4TJETGLeNBCs7ds9QewReg.png&w=600" alt="Screenshot of /casablanca" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/AW1-myPh8HgOFSAyBMsuJIXOE8qew_Z_J8Ltyd9hBNSqbbcclLOnNYt2r6DuyQM7vUUKnarKQBFpyHr8aA9PQA.png">(view full size)</a> |







Commit 5665a7255792e5657a347191253b39c63ad8e8b7 (https://counterspell-em14esi6b.hackclub.dev).

2024-10-14 05:44 UTC, samdev-7 requested changes

2024-10-14 05:44 UTC, samdev-7 commented on yarn.lock
The packages updated recently, you might need to re-run yarn install or revert this change.

2024-10-14 07:45 UTC, slippyishappy commented on yarn.lock
I've just updated the packages as you suggested. Let me know if there's anything else I need to do!

2024-10-14 16:28 UTC, samdev-7 commented on yarn.lock
Not sure what's happening with this file. Can you revert/restore this to what's on the main repo?

2024-10-15 11:06 UTC, slippyishappy commented on yarn.lock
I fetched the latest changes from this repo and rebased my branch. Is the file good to go now?

2024-10-16 10:45 UTC, samdev-7 requested changes
Not sure what happened here, but it seems like you’re trying to edit all previous cities?

2024-10-16 12:55 UTC, slippyishappy commented
I basically tried to fetch everything in this repo to mine, but since there are many issues, I can close this pr, fork this repo again, make my changes, and make a new pr.

2024-10-16 16:37 UTC, closed without merging