Updates to Counterspell Cambridge
hackclub/counterspell pull request #51
Opened 2024-10-13 21:43 UTC by mattsoh

2024-10-13 21:45 UTC, lachlanjc commented
#### 📝 Changed routes:


| [**/cambridge**](https://counterspell-aoysq5e16.hackclub.dev/cambridge) |
|:-:|
|<a href="https://counterspell-aoysq5e16.hackclub.dev/cambridge"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/LJwt0eWx_zQaQ1iWQwH2ty2vtVFej59gxiSUFuPcTfrpf4OsUK3L130IHr6fGiLSF514F79Y2wLhgrHr9tVZGg.png&w=600" alt="Screenshot of /cambridge" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/XYR9ubj4SmLRRHWB8m-y8xGpr7TPoHUSInYOtVDjFhR1lgEC66Gpe6WiTj0ZXvFOAWfmol-FeaC-C9PeFKU0ag.png">(view full size)</a> |







Commit 586b8f72bc4f466ae826e32911d876f416d71630 (https://counterspell-aoysq5e16.hackclub.dev).

2024-10-14 05:43 UTC, samdev-7 requested changes

2024-10-14 05:43 UTC, samdev-7 commented on yarn.lock
The packages updated recently, you might need to re-run yarn install or revert this change.

2024-10-14 13:26 UTC, mattsoh commented
@samdev-7

2024-10-14 16:26 UTC, samdev-7 approved these changes

2024-10-14 16:26 UTC, samdev-7 approved these changes

2024-10-14 16:27 UTC, merged