Added Sponsor Page
hackclub/counterspell pull request #62
Opened 2024-10-15 23:03 UTC by GaoYeGithub

2024-10-15 23:10 UTC, lachlanjc commented
#### 📝 Changed routes:


| [**/toronto**](https://counterspell-8t5zl8jj0.hackclub.dev/toronto) |
|:-:|
|<a href="https://counterspell-8t5zl8jj0.hackclub.dev/toronto"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/xqb_UfiWR7ZElOS7siLCk1SnpNesvcEDrk7QV_KTdcWqNxHXN95-AjAI-8_vZBAXYJhPEwMYU8jyxMEen-z9jg.png&w=600" alt="Screenshot of /toronto" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/ScO53lxsunGQv8mjFZXbCyy6-lVnz1jLY_0R10eUjU6QJF02-wbzsBrSn9XOYEPL5ZtqX58PGLMPBrYeQiRjNw.png">(view full size)</a> |







Commit 1aa8d15eed40aad69e8977f92f87f213bdaa58cc (https://counterspell-8t5zl8jj0.hackclub.dev).

2024-10-16 19:48 UTC, samdev-7 requested changes

2024-10-16 19:48 UTC, samdev-7 commented on eslintrc.json
Please revert this addition.

2024-10-16 19:48 UTC, samdev-7 commented on gitignore.txt
Please revert this addition.

2024-10-18 00:57 UTC, GaoYeGithub commented
Wait I having trouble they seem to be completely the same

2024-10-19 23:50 UTC, samdev-7 commented
You added `eslintrc.json` and `gitignore.txt`. The two files already exist as `.eslintrc.json` and `.gitignore`. Note the additional dot in front and lack of ".txt".

2024-10-20 02:36 UTC, GaoYeGithub commented
Oh, I didn't notice thanks so much for the help

2024-10-21 00:06 UTC, samdev-7 approved these changes

2024-10-21 00:06 UTC, merged