Changes to the language
hackclub/counterspell pull request #71
Opened 2024-10-20 02:34 UTC by Kakoobit

2024-10-20 02:35 UTC, Kakoobit reviewed
I've changed the language of the cards to spanish and the email for spanish faqs

2024-10-20 14:40 UTC, samdev-7 requested changes

2024-10-20 14:40 UTC, samdev-7 commented on public/cards/artist.png
For all 3 card images, please do not change the original. Put your updated versions in public/city/my-city-name/

2024-10-21 03:13 UTC, Kakoobit commented on public/cards/artist.png
Already did it. Can you check it?

2024-10-23 23:48 UTC, closed without merging