Adding Counterspell Gurugram
hackclub/counterspell pull request #78
Opened 2024-10-23 15:22 UTC by aryan9190

2024-10-23 15:23 UTC, lachlanjc commented
#### 📝 Changed routes:


| [**/gurugram**](https://counterspell-5hu43jg0r.hackclub.dev/gurugram) |
|:-:|
|<a href="https://counterspell-5hu43jg0r.hackclub.dev/gurugram"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/T7mdJes6c_-LHHjZB_r39fLJefnOuPnhu7po1o5kZkyO8Uw7nMYIqpK1iOp5uHurzJhBeBI3ZpnLJNI4YidiLg.png&w=600" alt="Screenshot of /gurugram" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/lVFhkdu_t6PR2Wc_cNP-YGZ75O7H8z8FWcM2PHGTYrp54snmc2u0ZpEg9St706EzvqoWIWuJeqitWFYoztcuaQ.png">(view full size)</a> |







Commit 8cb657ea882b49f7fba040411cb41ea88255d6b7 (https://counterspell-5hu43jg0r.hackclub.dev).

2024-10-24 21:03 UTC, samdev-7 requested changes

2024-10-24 21:03 UTC, samdev-7 commented on components/Gurugram/Hero.js
> +                NOVEMBER 23-24, 2024 • EXAMPLE CITY
This should be changed!

2024-10-25 13:39 UTC, aryan9190 reviewed
Did it

2024-10-31 04:42 UTC, samdev-7 approved these changes

2024-10-31 04:51 UTC, merged