Adding sign-up and scroll to Counterspell Minneapolis page
hackclub/counterspell pull request #83
Opened 2024-10-25 18:47 UTC by sophia-pung

Add Sign-Up Button and Scrolling Feature to Minneapolis Page

2024-10-25 20:47 UTC, AverseABFun commented
Just to be clear, this is approved my me, the organizer.

2024-10-29 04:09 UTC, samdev-7 requested changes
Some quick changes and it should be good to go!

2024-10-29 04:09 UTC, samdev-7 commented on 0001-adding-a-sign-up-button-and-scrolling-to-Counterspel.patch
Not sure why this file is here, could you remove it?

2024-10-29 04:09 UTC, samdev-7 commented on package.json
Please don't modify this file. Revert your changes, thanks!

2024-10-29 04:09 UTC, samdev-7 commented on package-lock.json
We use yarn `yarn install` & `yarn dev`. Please revert your changes on this file, thanks!

2024-10-29 04:09 UTC, samdev-7 commented on yarn.lock
Please don't modify this file. Revert your changes, thanks!

2024-11-30 06:34 UTC, samdev-7 commented
Closing this due to inactivity. Feel free to re-open if you still want these changes to be added.

2024-11-30 06:34 UTC, closed without merging