Add Counterspell Atlanta
hackclub/counterspell pull request #9
Opened 2024-10-02 04:59 UTC by aboutdavid

2024-10-02 05:02 UTC, samdev-7 requested changes

2024-10-02 05:02 UTC, samdev-7 commented on src/components/Locations.js
> +    "Atlanta, GA"
```suggestion
    "Oshkosh, WI"
```
Hold off on adding stuff here for now. We'll add it after registrations for organizers close.

2024-10-02 05:02 UTC, samdev-7 commented on src/index.js
> +        {<Route path="/atlanta" element={<Atlanta />} />}
```suggestion
        <Route path="/atlanta" element={<Atlanta />} />
```

2024-10-02 15:51 UTC, aboutdavid commented
squashed

2024-10-02 15:53 UTC, samdev-7 requested changes

2024-10-02 15:53 UTC, samdev-7 commented on src/index.js
> +import Atlanta from "./pages/Atlanta";
Can you move this line after the import ExampleCity comment?

2024-10-04 03:28 UTC, samdev-7 approved these changes

2024-10-04 03:29 UTC, merged