Adding Counterspell Saint Augustine
hackclub/counterspell pull request #93
Opened 2024-10-30 00:25 UTC by i-suck-at-most-stuff

Adding Counterspell Saint Augustine page, I followed the templete and im pretty sure i did everything right, i juts have to learn how to make the signup API.

2024-10-31 04:50 UTC, lachlanjc commented
#### 📝 Changed routes:


| [**/saint-augustine**](https://counterspell-o46wk0lj3.hackclub.dev/saint-augustine) |
|:-:|
|<a href="https://counterspell-o46wk0lj3.hackclub.dev/saint-augustine"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/8XYSDIE96-aK9Jy5_YskrB7VNNCjxbjWERA_gP4L8EdsuYcvbj61WqfXd9wFHJDWYZTqXrnfsJjsklBHXZ_6Ag.png&w=600" alt="Screenshot of /saint-augustine" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/RDjiVHLQGTfmQJof3XqqBDrlfA-qBcTaTay6xwNNnxHqc1P80bC6eKWceP_-GfO5AyyGuNTSG1VHRFLL4A4pLA.png">(view full size)</a> |







Commit 0a5664e23d118544bc271187783c3bcef678c66c (https://counterspell-o46wk0lj3.hackclub.dev).

2024-10-31 04:51 UTC, samdev-7 requested changes
Almost there! One quick change.

2024-10-31 04:51 UTC, samdev-7 commented on components/SaintAugustine/About.js
> +              schoolers happening in Example City where{" "}
You forgot to change out "Example City" here.

2024-10-31 11:04 UTC, i-suck-at-most-stuff commented
Sorry about that

2024-11-03 02:13 UTC, samdev-7 approved these changes

2024-11-03 02:14 UTC, merged