Counterspell Nairobi :)
hackclub/counterspell pull request #98
Opened 2024-10-31 13:43 UTC by v1peridae

-> Counterspell Nairobi Site
-> The changes on the Example City/About.j are from Prettier (sorry)

2024-11-02 02:36 UTC, lachlanjc commented
#### 📝 Changed routes:


| [**/nairobi**](https://counterspell-r1pyiyxll.hackclub.dev/nairobi) |
|:-:|
|<a href="https://counterspell-r1pyiyxll.hackclub.dev/nairobi"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/jfvkA6J8efndWPJ9BLc81iDOBRLDN0JbyQFxFpVGdMvvbq2yIsPeAVQ7sCayoTbxV8OVY01m85Ag-ZBbqzc45Q.png&w=600" alt="Screenshot of /nairobi" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/-xtv2wRJVl9R0PM02sO_8EOwG-XJNbFlKDQkXqr2R_CySMFnQXp9AcTSMr3ihlVzezZFeGRfY4I48YQBGY6oyg.png">(view full size)</a> |







Commit 52e12b79fad9b9b86b1c115d754dd76736fbca9e (https://counterspell-r1pyiyxll.hackclub.dev).

2024-11-02 02:37 UTC, samdev-7 requested changes

2024-11-02 02:37 UTC, samdev-7 commented on components/ExampleCity/About.js
This is the wrong file to edit. Please undo your changes to this file, thanks!

2024-11-03 17:37 UTC, v1peridae commented
@samdev-7 done :)) ty for pointing this out :)

2024-11-04 01:20 UTC, samdev-7 approved these changes

2024-11-04 01:26 UTC, merged