Counterspell Abu Dhabi
hackclub/counterspell pull request #99
Opened 2024-10-31 15:15 UTC by akulsaju

2024-11-02 02:44 UTC, samdev-7 requested changes
You need to make a copy of the example components. I'd check out how other cities do it in the `components` folder. Also, use `AbuDhabi` as the folder name, do not use spaces.

2024-11-02 07:23 UTC, akulsaju commented
@samdev-7 done

2024-11-03 02:16 UTC, samdev-7 requested changes

2024-11-03 02:16 UTC, samdev-7 commented on pages/abudhabi.js
> +import Footer from "../components/Abu Dhabi/Footer";
These imports are wrong. You'll need to remove the space.

2024-11-03 11:18 UTC, akulsaju commented on pages/abudhabi.js
> +import Footer from "../components/Abu Dhabi/Footer";
@samdev-7 done

2024-11-04 01:25 UTC, samdev-7 requested changes

2024-11-04 01:25 UTC, samdev-7 commented on pages/abudhabi.js
> +export default function Abu Dhabi() {
Same with here. I'd recommend that you try testing your changes locally with `yarn` and `yarn dev`!

2024-11-04 02:21 UTC, akulsaju commented
Done

On Mon, 4 Nov 2024, 5:25 am Sam Liu, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In pages/abudhabi.js
> <https://github.com/hackclub/counterspell/pull/99#discussion_r1827115966>:
>
> > +
> +import React, { useEffect, useRef, useState } from "react";
> +import useSound from "use-sound";
> +import Head from "next/head";
> +
> +// TODO: Change `ExampleCity` to the name of your city. This should match the folder you copied!
> +import Hero from "../components/AbuDhabi/Hero";
> +import About from "../components/AbuDhabi/About";
> +import Guilds from "../components/AbuDhabi/Guilds";
> +import Steps from "../components/AbuDhabi/Steps";
> +import Locations from "../components/AbuDhabi/Locations";
> +import Faq from "../components/AbuDhabi/Faq";
> +import Footer from "../components/AbuDhabi/Footer";
> +
> +// TODO: Change `ExampleCity` to the name of your city
> +export default function Abu Dhabi() {
>
> Same with here. I'd recommend that you try testing your changes locally
> with yarn and yarn dev!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/counterspell/pull/99#pullrequestreview-2412003459>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASKZKNGXNLNTLPCL256L743Z625IJAVCNFSM6AAAAABQ6QRQ6OVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMJSGAYDGNBVHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-04 03:46 UTC, samdev-7 commented
I don't see any changes. Make sure you’ve pushed the changes.

2024-11-05 04:09 UTC, samdev-7 requested changes

2024-11-05 04:09 UTC, samdev-7 commented on .github/workflows/nextjs.yml
You don't need to create this file!

2024-11-05 04:09 UTC, samdev-7 commented on pages/abudhabi.js
> +export default function Abu Dhabi() {
Please change this to AbuDhabi() 
The space is causing an error.

2024-11-05 11:57 UTC, akulsaju commented
I had fixed it before but didn't commit

On Tue, 5 Nov 2024, 8:10 am Sam Liu, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> On .github/workflows/nextjs.yml
> <https://github.com/hackclub/counterspell/pull/99#discussion_r1828697803>:
>
> You don't need to create this file!
> ------------------------------
>
> In pages/abudhabi.js
> <https://github.com/hackclub/counterspell/pull/99#discussion_r1828698063>:
>
> > +
> +import React, { useEffect, useRef, useState } from "react";
> +import useSound from "use-sound";
> +import Head from "next/head";
> +
> +// TODO: Change `ExampleCity` to the name of your city. This should match the folder you copied!
> +import Hero from "../components/AbuDhabi/Hero";
> +import About from "../components/AbuDhabi/About";
> +import Guilds from "../components/AbuDhabi/Guilds";
> +import Steps from "../components/AbuDhabi/Steps";
> +import Locations from "../components/AbuDhabi/Locations";
> +import Faq from "../components/AbuDhabi/Faq";
> +import Footer from "../components/AbuDhabi/Footer";
> +
> +// TODO: Change `ExampleCity` to the name of your city
> +export default function Abu Dhabi() {
>
> Please change this to AbuDhabi()
> The space is causing an error.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hackclub/counterspell/pull/99#pullrequestreview-2414583164>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASKZKNDQUO6EI2HZ6VRAZETZ7AZJJAVCNFSM6AAAAABQ6QRQ6OVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMJUGU4DGMJWGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-06 03:54 UTC, samdev-7 commented on .github/workflows/nextjs.yml
Please remove this file!

2024-11-06 03:55 UTC, samdev-7 commented
Remember to push/sync after you commit! I don't see any changes.

2024-11-06 15:24 UTC, akulsaju commented
@samdev-7 done

2024-11-06 17:28 UTC, samdev-7 approved these changes

2024-11-06 17:30 UTC, samdev-7 requested changes
Seems like the code is failing. You need to capitalize the file names in components/AbuDhabi.

2024-11-06 18:55 UTC, akulsaju commented
@samdev-7 updated the file names and made a few changes in Schedule.js

2024-11-09 18:00 UTC, lachlanjc commented
#### 📝 Changed routes:


| [**/abudhabi**](https://counterspell-gvj2vdnhw.hackclub.dev/abudhabi) |
|:-:|
|<a href="https://counterspell-gvj2vdnhw.hackclub.dev/abudhabi"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/uUs23Lk19-DkQMGvV7JrErQ2_0mM7jt58Ax7e1746pG3K_RFSfH3z27pUN0z27rKcZ98vQ4FdqD18rX7q2PsWw.png&w=600" alt="Screenshot of /abudhabi" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/v54LT5lMyok_yleMg1zUxF-OVF2GT5osxJSspsrVS3N2mqtUrVTjGASHrSEtYsrN2qaHuuwwW8VvvoPwQrT84Q.png">(view full size)</a> |







Commit ff533d566117518d5a1ba64a262df7ebb43f4214 (https://counterspell-gvj2vdnhw.hackclub.dev).

2024-11-09 18:02 UTC, samdev-7 approved these changes

2024-11-09 18:03 UTC, merged